sudo: false

language: node_js
node_js:
  - "10"
  - "9"
  - "8"

before_script:
  - npm install

script:
  - npm run build
  - npm run node-test

before_deploy:
  - mkdir -p exif-library/dist
  - cp ./dist/exif-library.js ./exif-library/dist
  - cp ./dist/exif-library.js.map ./exif-library/dist
  - cp ./dist/index.d.ts ./exif-library/dist
  - cp ./README.md ./exif-library/
  - cp ./package.json ./exif-library/
  - cp ./LICENSE.txt ./exif-library/
  - zip -r exif-library.zip ./exif-library
  - rm -rf exif-library
deploy:
  - provider: releases
    api_key: "${GITHUB_OAUTH_TOKEN}"
    file: exif-library.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: "${NPM_MYMAIL}"
    api_key: "${NPM_TOKEN}"
    skip_cleanup: true
    tag: beta
    on:
      tags: true
      condition: $TRAVIS_NODE_VERSION = 10
